name: Docker
on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Initialize the application
        run: sh ./run.sh
